insert into categorias (nombre, descripcion) values ('Crime|Drama|Thriller', null);
insert into categorias (nombre, descripcion) values ('Adventure|Animation|Children|Comedy', null);
insert into categorias (nombre, descripcion) values ('Comedy|Drama', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into categorias (nombre, descripcion) values ('Comedy|Drama', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into categorias (nombre, descripcion) values ('Drama', null);
insert into categorias (nombre, descripcion) values ('Drama|Romance|Thriller', 'In congue. Etiam justo. Etiam pretium iaculis justo.');
insert into categorias (nombre, descripcion) values ('Adventure|Animation|Children|Drama', null);
insert into categorias (nombre, descripcion) values ('Drama|Romance', null);
insert into categorias (nombre, descripcion) values ('Adventure|Comedy|Crime|Drama', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into categorias (nombre, descripcion) values ('Horror|Thriller', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.');