insert into usuarios (direccion, password, username, email) values ('PO Box 67160', '$2a$04$HqiLCO19MPEUWoApPDs3o.ea6Vm300BLvbT2hQGrRJkVoqaAQfH02', 'dphilipeau0', 'pveness0@about.me');
insert into usuarios (direccion, password, username, email) values ('7th Floor', '$2a$04$AGGEgER349P8QJyw9UV.8.ksoTf0fUvGKqJEMalEXhgOqC6gDi5me', 'rkollach1', 'okail1@a8.net');
insert into usuarios (direccion, password, username, email) values ('9th Floor', '$2a$04$AozqaZt/uzPQBkzTHXxSg.3sQ2mVS5/utDdGWuBRwBfdrkjdJNrM6', 'rscare2', 'aharmes2@ucla.edu');
insert into usuarios (direccion, password, username, email) values ('4th Floor', '$2a$04$OTG9E1pfyehdGhb8mSUU8evdMyhtVkmLT5u8yg0.MY2PzIFDOTaDK', 'zlevene3', 'sbertholin3@deviantart.com');
insert into usuarios (direccion, password, username, email) values ('Suite 9', '$2a$04$56BbfWX06l0HBRX5kSlpZOK/x0DdTdz/oaLicqLXnTXiRD7Z3Luqm', 'lduprey4', 'rbartolic4@privacy.gov.au');
insert into usuarios (direccion, password, username, email) values ('Room 164', '$2a$04$8J04leAxNfYmR7NlphjGMO9j08K6grU.DtNTbkhbhiMHL8yAs3Fz2', 'sfranzke5', 'hwingatt5@ifeng.com');
insert into usuarios (direccion, password, username, email) values ('Room 477', '$2a$04$bk9Ox0U/VnoL6ad7L4T4ueFnDtGxY.N5TlJVwwI9W6J6TKmsSBhi.', 'nstiant6', 'ssanderson6@xing.com');
insert into usuarios (direccion, password, username, email) values ('Suite 15', '$2a$04$vOqhQ1U6hLq5HOHR3NoOjO4tWadW5cGDbM0Ucc4TfqmJaqPfgn4ma', 'rsimonnin7', 'agreves7@prnewswire.com');
insert into usuarios (direccion, password, username, email) values ('Suite 58', '$2a$04$mZPqSnrUog7AXBqkekRUw.igI3A6bY1nXBeohGXFPGjD8D92glzf6', 'uakerman8', 'lstopford8@tripod.com');
insert into usuarios (direccion, password, username, email) values ('Room 1383', '$2a$04$0K.ql0H8Zp/2/qqbL2EuQOk0hSV2tbQ649aEh5jWPssPwfb/G4sGC', 'cfieller9', 'jdansie9@meetup.com');
insert into usuarios (direccion, password, username, email) values ('12th Floor', '$2a$04$KQd3RID8a9XTHgOX/TVkq.yh8OBRPxisiqaCHej8Kxn2qnXh8N2CK', 'hlambshinea', 'rfitcha@ft.com');
insert into usuarios (direccion, password, username, email) values ('Suite 32', '$2a$04$8qeIvy/mtbUw3mjSFccAE.WuMrdR3r13tgU2f0Xvax4FFpvF2lMrC', 'ischwandnerb', 'sfeldmanb@cpanel.net');
insert into usuarios (direccion, password, username, email) values ('PO Box 36136', '$2a$04$H4ImXR9.DsIKX6B3U19LjOt81GDmsLkUA6W9620OMMgOuYp.Z5ixG', 'aveldenc', 'lpatinkinc@wsj.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 53185', '$2a$04$OYUY10HlTPVK5RggCI/iLup8LCrnnlEG9nJagTv9uTYzRzFXiFdJm', 'jsmoothd', 'jmapholmd@yahoo.co.jp');
insert into usuarios (direccion, password, username, email) values ('20th Floor', '$2a$04$aQik0QfjilzowcsqihLUb.9c9DXbpvyNUozLd51XidvY4fBxOqzB6', 'ckanne', 'wbeardone@abc.net.au');
insert into usuarios (direccion, password, username, email) values ('Suite 32', '$2a$04$y90Y6SiHWwzzAMV3ODzOyOovHOwBizcPLSD/ZvsUmSa7YYq0oMPxq', 'jlatteyf', 'acosserf@google.pl');
insert into usuarios (direccion, password, username, email) values ('Apt 1571', '$2a$04$Uhom9eZg8ZRUUDtv3DupK.ouwSS8eHJ1KwUleUfcQ3gOIiCTc79Um', 'ciannellig', 'wdinzeyg@reuters.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 34756', '$2a$04$czzP11tkupJuDpJkXrY7g.buQ9UeRyFAuTRoS6V7oRlzCMvTfaC..', 'ahixsonh', 'twynessh@irs.gov');
insert into usuarios (direccion, password, username, email) values ('Room 91', '$2a$04$LK0bGIFHdFKjABO9uqZpU.11asMQWcEdMG9wA2Roesr1iW1kR1ugS', 'thailsi', 'rlaysoni@cloudflare.com');
insert into usuarios (direccion, password, username, email) values ('Room 1654', '$2a$04$uMbcuPeCM65yQI9kl6XXEeOt.3HZo6pFPWko4xwZ40sxfhTsjHZJC', 'jplayhillj', 'ncraciej@dot.gov');
insert into usuarios (direccion, password, username, email) values ('PO Box 81541', '$2a$04$u/TclrrhDBwmY2Ie6Bzc5O5LwRRAVX2HZtwu0cM8/eUkkwVidB7sK', 'cduncombek', 'fmacvanamyk@gov.uk');
insert into usuarios (direccion, password, username, email) values ('Apt 1352', '$2a$04$KugfBcLR41yxIwm.OR.kb.CzVOryjmeLtJAexEGQLaS7OjWK0ZFA2', 'bescudierl', 'nboldersonl@rediff.com');
insert into usuarios (direccion, password, username, email) values ('Room 1398', '$2a$04$x5QCQQppbvUcNU4TyrVnWuSHr2GFJ8UAzKuGGrzV9tSSY3KzmORO6', 'csnellingm', 'vcircuitm@skyrock.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 4130', '$2a$04$AAmY95foHwJnaqOGsEACOe75k7UHK.ph4tVHWhdrywgDUWnsjHWpO', 'mcrowcumn', 'dgoshawken@jugem.jp');
insert into usuarios (direccion, password, username, email) values ('Apt 1105', '$2a$04$UD/MxBj87wq9DmVsfdGJfu/zwy9.JBDouE.0vTkT.jaAtb22Hhazq', 'mdyetto', 'srobenso@freewebs.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 78709', '$2a$04$RNLIB7FCG4UNluOKslNAKOGkMBR8sr.xJL0l5vRii7JQ5ajXPAa3e', 'iazemap', 'dtordiffep@umich.edu');
insert into usuarios (direccion, password, username, email) values ('Room 1303', '$2a$04$z0zxreNGmXhWdh9llq.Xb.eqD1BqC5icIxDnrLCGQJvf.k4uMHJ5y', 'edumbarq', 'erollettq@cdbaby.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 61866', '$2a$04$Sr5HUkPcIWHs4ye64i6SOO/yUbClLG.g6f1KPQro3lCeXlPuUvDsS', 'gpincottr', 'cbartoccir@123-reg.co.uk');
insert into usuarios (direccion, password, username, email) values ('Suite 79', '$2a$04$X2XHxaL5zKH.yvpMk5zeUeXf6qXE1SZA1IetkGs4jPFTqhzlqea6K', 'jreys', 'wweetchs@blinklist.com');
insert into usuarios (direccion, password, username, email) values ('Suite 87', '$2a$04$W9m64F7NaL8UvWJ8EQZoHeQpHyd.vBv.PYVCc6rmQ7cpI4PD5I7ky', 'tgallahart', 'jquinevant@odnoklassniki.ru');
insert into usuarios (direccion, password, username, email) values ('Apt 910', '$2a$04$Oa8jYieoJsyhmHijH7hSGO3iNXoAA76FV9tfHIbM5.Yd/liNIkMpm', 'vfairfootu', 'epepineauxu@nymag.com');
insert into usuarios (direccion, password, username, email) values ('Suite 24', '$2a$04$/7kLJohPfATOXTgdArfXKufcVufaSnJi8ftn5ygXoGQrHaRdYl/uO', 'washlingv', 'szammettv@washington.edu');
insert into usuarios (direccion, password, username, email) values ('Room 75', '$2a$04$7efWKa2B/nCXDQbhX.SLbOk7Zpp2/LYPbVFMHfJfWgqqqlTMklrFK', 'bgorgesw', 'kryottw@admin.ch');
insert into usuarios (direccion, password, username, email) values ('PO Box 66681', '$2a$04$74hhsL/wB5S2TYVvnRruaOwoHyaHhDFp4cmB.u/ZjiylDyG2eM5/2', 'sferranx', 'rsmuthx@zimbio.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 27987', '$2a$04$7tXSnQ/zYzBHdzGG1hw09..15QuTyzc3qd94e8LEiSqkO8XR//eU6', 'mbigglestoney', 'bpratty@blog.com');
insert into usuarios (direccion, password, username, email) values ('15th Floor', '$2a$04$Ris30HiFhSJ2WOvgcaQvK.xY4pJi/og1iwa7Y/lDJqf.bUKq8k.wq', 'dfoucardz', 'lwillardz@google.de');
insert into usuarios (direccion, password, username, email) values ('PO Box 68364', '$2a$04$jVVhLjgLA4DQ6oIMkV.ek.yz9pu/WTP2oW9SJgDYpCHq2jv6ug3J6', 'gcicchelli10', 'ageldard10@tinypic.com');
insert into usuarios (direccion, password, username, email) values ('Apt 1216', '$2a$04$/iIRz1xzMtVYBDHZeiyMBe9rrWlJUhhzWDvJ2SnJqbjXDT8qkgj3y', 'pcoleford11', 'gdownie11@amazon.com');
insert into usuarios (direccion, password, username, email) values ('Suite 31', '$2a$04$635On2bOJwg9L0iNfiFBR.oGJGrP8KfsZ2qIb6/BsM/bSjyN./6ha', 'ebatteson12', 'gmaffia12@craigslist.org');
insert into usuarios (direccion, password, username, email) values ('18th Floor', '$2a$04$Z8jTVGPXlhuf6gOCK2I1Yu3AJuR8eRCD9e9ht0gNfY76t8sSJqkbK', 'gfalls13', 'roverall13@flavors.me');
insert into usuarios (direccion, password, username, email) values ('12th Floor', '$2a$04$lZILYffa/sEJDR44MUbi6eDxq6jlMLvSOrW6djMUavCa/08YVrqRa', 'ibrazear14', 'rrawood14@hibu.com');
insert into usuarios (direccion, password, username, email) values ('Suite 62', '$2a$04$xxuP8IERmstnlEDaWvQdAOPpR1HgJtJI.4SSh6mX/Jywmal/nB4uq', 'dshanahan15', 'gdulwich15@upenn.edu');
insert into usuarios (direccion, password, username, email) values ('Apt 872', '$2a$04$L8asC2zPUv9L2.v1dS0TJO.MInleAdShwru39vuUyFI/Ob.NFXvjG', 'kgallally16', 'gdoldon16@geocities.jp');
insert into usuarios (direccion, password, username, email) values ('10th Floor', '$2a$04$kR4hi2fxGrlEJjkFQBzU/OcGM/2SYWQyyB7p0XJ149mc6yqnrWWWO', 'amarkushkin17', 'jseide17@icq.com');
insert into usuarios (direccion, password, username, email) values ('Apt 46', '$2a$04$qWuU2612TgO3xBSOWtxoEuIBuMF1oS4DO/xL.n0ls3PGUS773YLMu', 'pdevoy18', 'elippiett18@goo.ne.jp');
insert into usuarios (direccion, password, username, email) values ('Suite 99', '$2a$04$oS0841lO2XxuHKUsA3kj6ORHX/1SYmcCN0wXflDF89cq1t8j0afAe', 'tghiron19', 'bwix19@timesonline.co.uk');
insert into usuarios (direccion, password, username, email) values ('Suite 56', '$2a$04$uNgQSVyuuviYawqjHbqZxe688A7WoxIwNiHRqvFtmXSk5KJQwojpi', 'opickless1a', 'njardein1a@mapquest.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 22873', '$2a$04$8UJ0EcHFijt9oYVGwEY98uBjuNJjigh7hvtedhvKLwlOHXvF7KOwm', 'mnuccii1b', 'rsarten1b@istockphoto.com');
insert into usuarios (direccion, password, username, email) values ('Room 593', '$2a$04$8qzQRbNcHJ5qji87/awABOsbKWLQpYonEt1r23xibghBV6Eb22wly', 'arookeby1c', 'afranek1c@cam.ac.uk');
insert into usuarios (direccion, password, username, email) values ('Apt 1489', '$2a$04$uiXhNC.R50T7H0ES67/sBuQd6RwtSREYOiaeYQa8fl1Ep9ooYBnfq', 'pmale1d', 'ddobie1d@cam.ac.uk');
insert into usuarios (direccion, password, username, email) values ('Room 1727', '$2a$04$ako8dGAXlTWm0/DvYVrXCOpW8BtwN5bY/zbEuSCSScCeKGRNwI0YK', 'ffonzo1e', 'bsyplus1e@ehow.com');
insert into usuarios (direccion, password, username, email) values ('Apt 330', '$2a$04$may7FYaSnmMWjhUX9lpBQu7NeM16iFCRDDalq1hffiJUoKMSSBq8S', 'agoodhay1f', 'fcurnok1f@squarespace.com');
insert into usuarios (direccion, password, username, email) values ('Suite 52', '$2a$04$Kwn/FI/UULXZVX6sWhJiLOLCiGXRacQeuKXVghTFdJQw6fL35le4y', 'jgrevel1g', 'fblythin1g@samsung.com');
insert into usuarios (direccion, password, username, email) values ('Suite 48', '$2a$04$NYjqKMsuvl2ENVGlZxLvkeHJ7F2tvlBORmumw4bTR/kn6SJ6kQ5gy', 'amacmorland1h', 'obyway1h@geocities.jp');
insert into usuarios (direccion, password, username, email) values ('19th Floor', '$2a$04$JOMXTufIWDRhRXjd1KRXb.ZdBJmieXNROvYDqK5Jh3ajEqa/XiuKK', 'mtant1i', 'ctreend1i@mlb.com');
insert into usuarios (direccion, password, username, email) values ('Suite 73', '$2a$04$10uZM7FlWx3UPItXTobake9K18jDbkya6PUGAVuJu7s7pOWILI6WS', 'pneames1j', 'hsneezum1j@wikipedia.org');
insert into usuarios (direccion, password, username, email) values ('9th Floor', '$2a$04$aHKw.50NePnI8eF1eLX4beEXByBRUZo.8BWsZGgEMBlFhqyE1TFTW', 'ubridgwood1k', 'johollegan1k@fastcompany.com');
insert into usuarios (direccion, password, username, email) values ('Apt 624', '$2a$04$3UOgTGUXDaAOfThkA1o/tO2aDLyDEqraWR3wzFBM3v1dnMmav7rq6', 'dedmonston1l', 'lcorradi1l@patch.com');
insert into usuarios (direccion, password, username, email) values ('Room 1407', '$2a$04$YBL/HPBfM4rVLvAq6VnXEOU1gLUN.vbK.0JrVVULmRtsJRVgBsEc6', 'dsiveyer1m', 'gewells1m@themeforest.net');
insert into usuarios (direccion, password, username, email) values ('8th Floor', '$2a$04$Ny0PGw8uJLnuzP2Lg/oMPu9uN9W/lHS6BJYWrnuHz/xzshWwUFG3e', 'sschlagh1n', 'vjacobowicz1n@vinaora.com');
insert into usuarios (direccion, password, username, email) values ('Room 1943', '$2a$04$5GAROubwwVRr3MmkOU1zBeTp.KkX0R8JBjcwADV.RIjaaBcfe3hD.', 'svasiliu1o', 'bpedracci1o@princeton.edu');
insert into usuarios (direccion, password, username, email) values ('Room 1694', '$2a$04$MV.eMkJh1sUGvqhXYtk49emPVoL29M2G0AZ8G8Z0yjVJiR.5Yjm1G', 'mandrzej1p', 'sfarrow1p@cbc.ca');
insert into usuarios (direccion, password, username, email) values ('Suite 97', '$2a$04$QD6cch0fe97WlRmUvVy75eOV3AQJ0m5FJ6E3so.//wRVU1zP2/F3i', 'lwebber1q', 'bberard1q@hhs.gov');
insert into usuarios (direccion, password, username, email) values ('Room 1648', '$2a$04$GNWKZYNt.HFcYLjnnj.4tOQi27qigGLoAgcUv1v6DOMKbhurzQ0ca', 'awinterbotham1r', 'gaharoni1r@altervista.org');
insert into usuarios (direccion, password, username, email) values ('Suite 100', '$2a$04$8YgAHXY/hVSHJ5064ghJ7uvmXkIPr4SOEvWEVeB936DkekLtc8opO', 'gspofforth1s', 'cmarshalleck1s@archive.org');
insert into usuarios (direccion, password, username, email) values ('PO Box 39765', '$2a$04$X7uCtSjMK1pzn9WedaFchunW.bilnZTT.XeaI24IYsbM7t8BSVxP6', 'rhonisch1t', 'tmcglade1t@phpbb.com');
insert into usuarios (direccion, password, username, email) values ('Suite 77', '$2a$04$d.wrMnqoT.PStynxLhzce.DnYMdAVKcXUyILs1rsbk.cPTKXAp2Ce', 'mstrettell1u', 'alighterness1u@cbc.ca');
insert into usuarios (direccion, password, username, email) values ('PO Box 95261', '$2a$04$Tm4cqU4dyCRD1uxevkQX5.2rBX9iP3Z6xc5VM5fn0q2J9we/itSIu', 'mtucknutt1v', 'clavelle1v@is.gd');
insert into usuarios (direccion, password, username, email) values ('Apt 539', '$2a$04$I71/9L97i.MCJrM0S9A/9.8u52YSEnHfycWRTBfnvYYBwRRW8h60O', 'boganian1w', 'adurant1w@jiathis.com');
insert into usuarios (direccion, password, username, email) values ('Apt 1378', '$2a$04$dyTS7AcWs07ch5qLKnMdguZWMnzKnV7Zf.JL3yW1TJkLBwHftnPqK', 'pcarnock1x', 'dwalden1x@ning.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 95553', '$2a$04$9DuD4fPnKrzKkBq4ftPCA.nCPUimJb0RmimAwGJvDDxq8Fn5h231W', 'mmatous1y', 'abackes1y@angelfire.com');
insert into usuarios (direccion, password, username, email) values ('Room 78', '$2a$04$tm5KWMT0qfj6uvBMG/Y8c.fYsmjo.iHTHQDEh1NQmmLCJrTjlrxVu', 'brothchild1z', 'mmains1z@samsung.com');
insert into usuarios (direccion, password, username, email) values ('Room 341', '$2a$04$xleut1GurikZ1OGhev88kOJKr6JOP0b46U2A8fIpCjLzvv0U1i9h2', 'ahaldene20', 'ochiene20@reference.com');
insert into usuarios (direccion, password, username, email) values ('Room 500', '$2a$04$marHJ12h0NtTDnjKY2mfXuzIbAP6.tMa4fzJtXQExoMJa9DLGCxia', 'cmecozzi21', 'kkeirle21@hp.com');
insert into usuarios (direccion, password, username, email) values ('Suite 44', '$2a$04$wrK0NfOa7YDJE/pJCbQAnOmsRoOGZ8ZIor1.U0tk3eHGfy/2UQF3m', 'jbarette22', 'speiro22@berkeley.edu');
insert into usuarios (direccion, password, username, email) values ('PO Box 6189', '$2a$04$8NwEoY9uAP9VSTyi.qlSVeVG93wLt9KnKcezG/JBBJkVav.cN1rpO', 'mlivesley23', 'fdomel23@baidu.com');
insert into usuarios (direccion, password, username, email) values ('Apt 327', '$2a$04$.wQdfskKJfKfHhNJoyBDFeKVvvvxGpBb2P.FpNH17gnvudrQaBj6q', 'zfilippello24', 'tganiford24@gnu.org');
insert into usuarios (direccion, password, username, email) values ('PO Box 10233', '$2a$04$RXR/9mX9LZ9fWbmPIf/PyOLpZ7m1YZL3XHVgJptf4bd7.EIX84R/C', 'gmachent25', 'drusson25@skyrock.com');
insert into usuarios (direccion, password, username, email) values ('Room 1808', '$2a$04$282RUnvyAug8OdKLno7BVu8VN805G4K2DFzBnJCsUlGqZ7//yEwvW', 'kbyard26', 'mangeau26@example.com');
insert into usuarios (direccion, password, username, email) values ('Apt 341', '$2a$04$fdE1mhJ2e.q6kB5UhOFqx.NURLtSwotlvfWA8FG4RiuM8j1ZmEK6G', 'nellery27', 'apeirazzi27@storify.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 62227', '$2a$04$kUZBVvXgKWPiVngq8lj88Ok2ZpLH5vZ7SN3G01zmjXzbVtHohKbn.', 'wolivie28', 'ccoller28@51.la');
insert into usuarios (direccion, password, username, email) values ('PO Box 5336', '$2a$04$kBalGvnUfXSHq9v56wcKOetwpY23lOj7uBOPR.vpxy1rCF0h1gwSK', 'adalyell29', 'dkahn29@sun.com');
insert into usuarios (direccion, password, username, email) values ('Suite 9', '$2a$04$NCMMFIBEh8gLAfMrhFJVCeURJsr2xuCcuDoDSviILihgXk//Rc6cy', 'acrotch2a', 'bgoulborn2a@goo.ne.jp');
insert into usuarios (direccion, password, username, email) values ('PO Box 75900', '$2a$04$5ivLZhySYHrDmF0qTlw0NOidVwC1Nnt9dteRpFxcFI56zuGJMewJC', 'nleyban2b', 'lphlipon2b@webeden.co.uk');
insert into usuarios (direccion, password, username, email) values ('Suite 100', '$2a$04$Je7os9XpySdOzaE3AQi/keFJizyA5Oe83J5MtmyuzMoUxO71gIpx.', 'jdunk2c', 'gjansik2c@newsvine.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 20874', '$2a$04$zU4Mv3.G42wfMrCvVhYWVe/bu8GuTlw7uhkvyhtsHWHE.1SZThFai', 'erotchell2d', 'socollopy2d@marketwatch.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 2592', '$2a$04$vG8wut9Y1epYnB9BpM1FjOakEd.FgshNEK3ivuS5habgION.UcXb6', 'gbranthwaite2e', 'fvanderhoeven2e@jalbum.net');
insert into usuarios (direccion, password, username, email) values ('15th Floor', '$2a$04$7qV/alBAvEo8kAm.UMNH3OucTkUCuZMN0wcsgyQRoffEMQRtQ278m', 'ejanisson2f', 'abarczynski2f@cnbc.com');
insert into usuarios (direccion, password, username, email) values ('Room 533', '$2a$04$y5cF1K6suwIJsg2lGlkR3OSXU/bkUU9oUTd1kgUkQ0C/GCk8NkaVa', 'wrubra2g', 'scolombier2g@nbcnews.com');
insert into usuarios (direccion, password, username, email) values ('Suite 4', '$2a$04$GWXi5/LZ6li95BKipwrR1ej1R1B1Fm8JMOx6K.oYwiy04.qvt092W', 'cscholes2h', 'esaull2h@google.com.hk');
insert into usuarios (direccion, password, username, email) values ('Apt 1487', '$2a$04$UqiiIA3BQ2/gGfsIvb4RAeUvDtoOjqMpA1c0m8ef7RJMK8mHg4Ety', 'tmckiernan2i', 'rrevie2i@sciencedirect.com');
insert into usuarios (direccion, password, username, email) values ('4th Floor', '$2a$04$HkdQ6Epg7iJOffaYL1PFWOnteHlA.3YG680JkQh5uxxf7wzGqo80S', 'dbraban2j', 'vpingstone2j@artisteer.com');
insert into usuarios (direccion, password, username, email) values ('Apt 1064', '$2a$04$Mj9eINklXY7lHL/LE8wACO52DWvCXXRqjAJdypIwRqdc8BU5dFl4K', 'pkennford2k', 'ereffe2k@stanford.edu');
insert into usuarios (direccion, password, username, email) values ('PO Box 49907', '$2a$04$HPDKEQDuu.nSiY/Xp.8EteIBDpgWPTjA7F7Vr9ISqkQ/kYKSxzxNK', 'esyers2l', 'mjarratt2l@dropbox.com');
insert into usuarios (direccion, password, username, email) values ('Suite 46', '$2a$04$DNG01HyQM3CHviimevhA7.hvJGfnYKTWTGtMMedxRo86AgRBxMIse', 'cmunslow2m', 'nbendle2m@shutterfly.com');
insert into usuarios (direccion, password, username, email) values ('7th Floor', '$2a$04$N6QZVszem1QwE1loC00aZOV2exjZVElny5XryrOZB/SqxBGbAgHN.', 'ttommaseo2n', 'mcattlow2n@chicagotribune.com');
insert into usuarios (direccion, password, username, email) values ('19th Floor', '$2a$04$5hmof0EYK1uATnLuiwNMGunbOG/C73Wjii3nph/KnKZvWIX76dwh.', 'kkingsnod2o', 'mneighbour2o@tripadvisor.com');
insert into usuarios (direccion, password, username, email) values ('PO Box 98926', '$2a$04$e4g6LTWboyHpLasQPZCNWO5Bkm7CPPM.7Eql.KoZiq6kO5nSFP4IS', 'tsoldner2p', 'lbourthouloume2p@chronoengine.com');
insert into usuarios (direccion, password, username, email) values ('Suite 62', '$2a$04$D1j2quEKBopV2Xnexz1PcOcYS9PdUPjycLmHuQQRwrZk3EqyaihWC', 'bwegman2q', 'bjepperson2q@thetimes.co.uk');
insert into usuarios (direccion, password, username, email) values ('2nd Floor', '$2a$04$yj08cGVFfV3Or5RGftbtFuQE48p712oTDqlI5Ua2.2QJT3vTS2CLm', 'rshearwood2r', 'hhofer2r@webeden.co.uk');